### ISSUE TITLE
void

### ISSUE THREAD

**Issue by abebeos** [Constellation-Labs/documentation-hub#57]

**Comment by AlexBrandes** [comment]
Hi @abebeos 
Thanks for the suggestion but the elaborative tone is intended. These docs are aimed at individuals running validator nodes which tends to be a less technical audience. The audience are not necessarily familiar with software development at all.

**Comment by abebeos** [comment]
> the elaborative tone is intended

this tone is simply exhausting, and the elaborations are not even to the point.

> We can now pull down the latest release from Constellation Network's repository.

> VERY IMPORTANT
> When downloading Tessellation...

> MAKE SURE YOU USE THE CORRECT VERSION!
> Installing an older or incorrect version could lead to unexpected results.

Then you provide 5 wget cli lines with versions that need to be checked manually.

You document, instead of "simplifying-then-documenting".

You need to find a way to simplify this, thus (non-power users) can install without the hassle of manual verification. How? Find a way - don't just document).

(e.g. using https://github.com/Constellation-Labs/tessellation/releases/latest somehow)

**Comment by abebeos** [comment]
(strictly, this issue would go into the tessellation repo. Once "streamline Binary Installation / simplify latest release download" is solved, the documentation would be updated.)

**Comment by abebeos** [comment]
@AlexBrandes , #59 clarifies what this is about. Documentation is simplified whenever possible, eliminating technical debt more and more. What i suggest is to do this going deeper and deeper into the code, making things simpler than with any other platform.

Let me know if this is of interest to you (context freelance / bounty work).
