### ISSUE TITLE
Base url not founf

### ISSUE THREAD

**Issue by prateushsharma** [Constellation-Labs/documentation-hub#99]
https://github.com/Constellation-Labs/documentation-hub/blob/main/hypergraph/API/01-global-apis.md

Base urls​:[​](https://docs.constellationnetwork.io/hypergraph/global-apis#base-urls-1)

    TestNet: https://l0-lb-testnet.constellationnetwork.io/
    IntegratioNet: https://l0-lb-integrationnet.constellationnetwork.io/
    MainNet: https://l0-lb-mainnet.constellationnetwork.io/
    
    after clicking them its telling not found

**Comment by IPadawans** [comment]
Hey @prateushsharma these URLs without the endpoints will return 404 not found. Take a look at the APISpecs where you'll see the endpoint, such as https://l0-lb-testnet.constellationnetwork.io/cluster/info
